name: プルリクエストを承認時ディプロイする

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - staging
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4
      - name: dist以外のファイルが存在しないかチェック
        run: |
          line="abcde"
          if ! echo "$line" | grep -q "dist/"
          then
              echo "Error: dist以外のディレクトリが存在します。($line)"
              exit 1
          fi

