name: Deploy on PR Approval

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 14.21.3
            cache: 'npm'
            cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to deployed branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b deployed
          git add .
          git commit -m "Deploy from PR approval"
          git push origin deployed --force
