name: プルリクエストを承認時ディプロイする

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - staging
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# defaults:
#   run:
#     shell: bash
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4
      - name: dist以外のファイルが存在しないかチェック
        run: |
          # bash -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo 1 > test.txt
          git add .
          git status --porcelain | while read -r line
          do
              if ! echo "$line" | grep -q "dist/"
              then
                  echo "Error: dist以外のディレクトリが存在します。($line)"
                  exit 1
              fi
          done
